'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    'NOTE: This file is auto-generated; do not modify it directly.  To make changes,
    ' or if you encounter build errors in this file, go to the Project Designer
    ' (go to Project Properties or double-click the My Project node in
    ' Solution Explorer), and make changes on the application tab.
    '
    Partial Friend Class Myapplication
        
        <Global.System.Diagnostics.DebuggerStepThroughattribute()>  _
        Public Sub New()
            MyBase.New(Global.Microsoft.VisualBasic.applicationServices.authenticationMode.Windows)
            Me.IsSingleInstance = false
            Me.EnableVisualStyles = true
            Me.SaveMySettingsOnExit = true
            Me.ShutDownStyle = Global.Microsoft.VisualBasic.applicationServices.ShutdownMode.afterMainFormCloses
        End Sub
        
        <Global.System.Diagnostics.DebuggerStepThroughattribute()>  _
        Protected Overrides Sub OnCreateMainForm()
            Me.MainForm = Global.BetterFreightProgram.Main
        End Sub
    End Class
End Namespace
