'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedattribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeattribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableattribute(Global.System.ComponentModel.EditorBrowsableState.advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.applicationSettingsBase
        
        Private Shared defaultInstance as MySettings = CType(Global.System.Configuration.applicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler as Boolean

    Private Shared addedHandlerLockObject as New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeattribute(), Global.System.ComponentModel.EditorBrowsableattribute(Global.System.ComponentModel.EditorBrowsableState.advanced)> _
    Private Shared Sub autoSaveSettings(sender as Global.System.Object, e as Global.System.Eventargs)
        If My.application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() as MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            addHandler My.application.Shutdown, addressOf autoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameattribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeattribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedattribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordattribute("My.Settings")>  _
        Friend ReadOnly Property Settings() as Global.BetterFreightProgram.My.MySettings
            Get
                Return Global.BetterFreightProgram.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
